version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Install awscli
          command: |
            sudo apt-get install -y python-pip
            sudo pip install awscli
      - run:
          name: Configure AWS Access Key ID
          command: |
            aws configure set aws_access_key_id \
            ${AWS_ACCESS_KEY_ID} \
            --profile default
      - run:
          name: Configure AWS Secret Access Key
          command: |
            aws configure set aws_secret_access_key \
            ${AWS_SECRET_ACCESS_KEY} \
            --profile default
      - run:
          name: Configure AWS region
          command: |
            aws configure set region ${AWS_REGION} \
            --profile default     
      - run:
          name: Create a Jar file of Lambda
          command: |
            pwd
            ls -al
            cd Email
            pwd ls -al
            sudo apt install maven
            mvn install
      - run:
          name: Create Zip
          command: |
           pwd
           ls -al
           cd Email/target
           zip -r csye6225-lambda-${CIRCLE_BUILD_NUM}.zip  Email-1.0-SNAPSHOT.jar      
      - run:
          name: Copy Artifact to S3 & update lambda
          command: |
           pwd
           ls -al
           aws s3 cp Email/target/csye6225-lambda-${CIRCLE_BUILD_NUM}.zip s3://${S3_LAMBDA_BUCKET}/csye6225-lambda-${CIRCLE_BUILD_NUM}.zip
           cd Email/target
           aws lambda update-function-code --function-name  csye-demo --zip-file fileb://csye6225-lambda-${CIRCLE_BUILD_NUM}.zip